services:
  mysql:
    environment:
      - MYSQL_DATABASE=filescloud
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=admin
  #  redis:
  #    image: redis:7.2
  #    ports:
  #      - 6379:6379

  minio:
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password


