services:
  mysql:
    restart: always
    image: mysql:8.1
    environment:
      - MYSQL_DATABASE=filescloud
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=admin
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
#  redis:
#    image: redis:7.2
#    ports:
#      - 6379:6379

  minio:
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio:/data

volumes:
  mysql:
  minio: