services:
  mysql:
    restart: always
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=filescloud
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=admin
  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - data/redis:/data
  minio:
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - data/minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password

volumes:
  mysql:
  minio:
  redis:

