services:
  mysql:
    restart: always
    image: mysql:8.1
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  #  redis:
  #    image: redis:7.2
  #    ports:
  #      - 6379:6379

  minio:
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data

volumes:
  mysql:
  minio:

