version: '3.9'

services:
  mysql:
    container_name: 'mysql'
    restart: always
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MYSQL_DATABASE: filescloud
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_USER: ${SQL_USER}
  redis:
    container_name: 'redis'
    restart: always
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
  minio:
    container_name: 'minio'
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  app:
    container_name: 'app_filescloud'
    restart: always
    image: romanv79/filescloud:v1.0.2
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MYSQL_USER: ${SQL_USER}
      MYSQL_PASSWORD: ${SQL_PASSWORD}
    depends_on:
      - mysql
      - redis
      - minio

volumes:
  mysql:
  minio:
  redis:

