services:
  mysql:
    restart: always
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      MYSQL_DATABASE: filescloud
      MYSQL_PASSWORD: ${SQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      MYSQL_USER: ${SQL_USER}
  redis:
    restart: always
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - /data
  minio:
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password

volumes:
  mysql:
  minio:
  redis:

