version: '3.9'

services:
  mysql:
    container_name: 'mysql'
    restart: always
    image: mysql:8.1.0
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: filescloud
      MYSQL_PASSWORD: pass12345678
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: roman
  redis:
    container_name: 'redis'
    restart: always
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  minio:
    container_name: 'minio'
    restart: always
    image: bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: miniopas

volumes:
  mysql:
  minio:
  redis:

