spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/filescloud
    username: roman
    password: pas12345678

  data:
    redis:
      host: localhost
      port: 6379

  session:
    timeout: 86400

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  root_bucket_name: user-files
  endpoint: http://127.0.0.1:9000
  access_key: admin
  secret_key: miniopas