spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filescloud
    username: admin
    password: password

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

#  session:
#    timeout: 86400


minio:
  endpoint: http://127.0.0.1:9000
  user_id: minio
  password: password