spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      port: 6379

  session:
    timeout: 86400

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  root_bucket_name: user-files